/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32l4xx.h"
#include <stdint.h>

#define PIN_5		(1U<<5)
#define LED_PIN		PIN_5
#define GPIOAEN		(1U<<0)


int main(void)
{
	RCC  ->AHB2ENR |= GPIOAEN;
	GPIOA->MODER   |= (1U<<10);
	GPIOA->MODER   &=~(1U<<10);
    /* Loop forever */
	for(;;)
	{
		GPIOA ->ODR ^=LED_PIN;
		for(int i=0; i<100000; i++);
	}

}
