/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "i2c.h"

/* Variables*/
const uint8_t msg[] 	= "VAMSI";
uint8_t* ptxbuf     	= (uint8_t*)msg;
uint8_t tx_size			= sizeof(msg);
volatile uint8_t tx_idx = 0;

uint8_t rx_buf[sizeof(msg)];
uint8_t rx_size			= sizeof(msg);
volatile uint8_t rx_idx = 0;

/*Function Prototypes */
static void I2C3_MasterCommunicate (void);

/* Main Loop */
int main(void)
{

	I2C1_SlaveConfiguration	 ();
	I2C3_MasterConfiguration ();

	I2C3_MasterCommunicate	 ();
    /* Loop forever */
	for(;;);
}


/* Function definition */
static void I2C3_MasterCommunicate (void)
{
	// Provide the address of the slave
	I2C3->CR2 |= SLAVE_OWN_ADDRESS;

	// Configure the addressing mode (0 indicates 10bit address, 1 indicates 7bit address)
	I2C3->CR2 &=~(1U<<11);

	// Provide the number of bytes to be sent
	I2C3->CR2 |= (tx_size<<16);

	// Configure the automatic end mode to stop the clock when N bytes of data is sent
	I2C3->CR2 |= (1U<<25);

	// Generate the START condition
	I2C3->CR2 |= (1U<<13);

	// Keep sending until the STOP condition is reached (Since automatic stop is used, the STOP bit will be set automatically)
	while(!(I2C3->ISR & (1U<<5)))
	{
		// First, check if there is no on-going transmission and the module's transmit buffer is empty
		if(I2C3->ISR & (1U<<1))
		{
			// Copy the data needed to be sent to the module's transmit buffer
			I2C3->TXDR = (*ptxbuf++);
		}


	}

	// Clear the STOP flag after sending the data so that the next time this function is used STOP flag is not PRESET
	I2C3->ICR |= (1U<<5);

}
